# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Fast-API basics Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout do código
      uses: actions/setup-python@v3
      

    - name: Instalar python
      uses: action/setup-python@v4
      with:
        python-version: '3.12'

    - name: instalar poetry
      run: |
        curl -sSl https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH

    - name: Instalar dependências com poetry
      run: |
        poetry install --no-interaction --no-root

    - name: Rodar testes
      run: |
        poetry run pytest --maxfail=1 --disable-warnings -q  

